spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.151:8848
    sentinel:
      transport:
        dashboard: 192.168.0.151:8858
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
#ipAddr: 120.79.50.189
ipAddr: 192.168.0.151
server:
  port: 12000
